org.gradle.configuration-cache=false
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.jvmargs=-Xmx4g -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8
org.gradle.configureondemand=false

wormholesVersion=2.2.0
minecraftVersion=26.3
bukkitMinecraftRange=26.1.2-26.3
fabricLoaderVersion=0.19.5
forgeVersion=26.3-66.0.8
neoForgeVersion=26.3.0.33-beta
