pluginManagement {
    repositories {
        maven { url = uri('https://maven.fabricmc.net/') }
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'wormholes-fabric'
include(':core')
project(':core').projectDir = file('../../core')
include(':optics')
project(':optics').projectDir = file('../../optics')

apply from: file('../../gradle/localization-settings.gradle')
