package art.arcane.wormholes.localization;

import art.arcane.volmlib.util.localization.LanguageFileHeader;

import java.util.List;
import java.util.Map;

final class WormholesLanguageHeader {
    private static final Map<String, String> VARIABLES = Map.ofEntries(
            Map.entry("access", "Portal access policy"),
            Map.entry("address", "Network peer address"),
            Map.entry("after", "Message value after editing"),
            Map.entry("allocation", "Pocket space allocation"),
            Map.entry("amount", "Vault currency travel cost"),
            Map.entry("argument", "Unexpected command argument"),
            Map.entry("before", "Message value before editing"),
            Map.entry("biome", "Biome identifier"),
            Map.entry("blacklisted", "Blocked players"),
            Map.entry("block", "Selected block material"),
            Map.entry("blocks", "Placed blocks affected by rebuilding"),
            Map.entry("cancel", "Chat input cancellation word"),
            Map.entry("code", "Server or portal invitation code"),
            Map.entry("color", "Selected display color"),
            Map.entry("command", "Command path"),
            Map.entry("containers", "Nonempty containers affected by rebuilding"),
            Map.entry("cost", "Portal creation or travel cost"),
            Map.entry("count", "Number of portals, destinations, or messages"),
            Map.entry("degrees", "Image rotation in degrees"),
            Map.entry("depth", "Projection depth"),
            Map.entry("description", "Message description"),
            Map.entry("destination", "Travel destination"),
            Map.entry("detail", "Additional diagnostic details"),
            Map.entry("diagnostic", "Diagnostic message"),
            Map.entry("direction", "Travel or facing direction"),
            Map.entry("door", "Pocket exit door"),
            Map.entry("duration", "Player-specific update interval"),
            Map.entry("endpoint", "Wormhole endpoint identifier"),
            Map.entry("entities", "Affected entity count or entity update interval in ticks"),
            Map.entry("entity", "Entity update interval in ticks"),
            Map.entry("error", "Error from the last operation"),
            Map.entry("facing", "Portal facing direction"),
            Map.entry("failed", "Number of failed operations"),
            Map.entry("fallback", "Alternative travel result"),
            Map.entry("fingerprint", "Public key fingerprint"),
            Map.entry("free", "Available random destination slots"),
            Map.entry("grace", "Projection grace period in seconds"),
            Map.entry("group", "Language editor category"),
            Map.entry("id", "Object identifier"),
            Map.entry("incoming", "Incoming travel policy"),
            Map.entry("item", "Required travel item"),
            Map.entry("key", "Message or configuration key"),
            Map.entry("kind", "Door access type"),
            Map.entry("label", "Display label"),
            Map.entry("large_step", "Adjustment amount when shift-clicking"),
            Map.entry("line", "Line number within a message"),
            Map.entry("locale", "Language code"),
            Map.entry("material", "Pocket wall material"),
            Map.entry("maximum", "Maximum allowed value"),
            Map.entry("message", "Feedback message"),
            Map.entry("minimum", "Minimum allowed value"),
            Map.entry("mode", "Travel or display mode"),
            Map.entry("name", "Portal or player name"),
            Map.entry("next", "Next available option"),
            Map.entry("node", "Network node identifier"),
            Map.entry("none", "Label for no linked destination"),
            Map.entry("other", "Linked endpoint identifier"),
            Map.entry("outgoing", "Outgoing travel policy"),
            Map.entry("owner", "Portal owner"),
            Map.entry("page", "Current page number"),
            Map.entry("pages", "Total number of pages"),
            Map.entry("parameter", "Command parameter name"),
            Map.entry("path", "File or directory path"),
            Map.entry("personal", "Personal language code"),
            Map.entry("plugin", "Plugin name"),
            Map.entry("portal", "Portal name or identifier"),
            Map.entry("prefix", "Beginning of a portal import code"),
            Map.entry("previous", "Previous pocket size in blocks"),
            Map.entry("quality", "Projection stream quality"),
            Map.entry("quantity", "Required item count"),
            Map.entry("range", "Portal activation range in blocks"),
            Map.entry("readiness", "Random destination readiness state"),
            Map.entry("reason", "Reason for an error or decision"),
            Map.entry("receive", "Projection receiving state"),
            Map.entry("refresh", "Projection refresh interval in ticks"),
            Map.entry("reserved", "Reserved random destination slots"),
            Map.entry("resized", "Number of rebuilt pockets"),
            Map.entry("rotation", "Projection rotation"),
            Map.entry("route", "Attempted travel route"),
            Map.entry("rtt", "Network round-trip latency"),
            Map.entry("seconds", "Time in seconds"),
            Map.entry("send", "Projection sending state"),
            Map.entry("server", "Server name or identifier"),
            Map.entry("size", "Pocket size in blocks"),
            Map.entry("skin", "Selected portal skin"),
            Map.entry("skipped", "Number of skipped operations"),
            Map.entry("space", "Pocket space identifier"),
            Map.entry("state", "Current access, link, or network state"),
            Map.entry("step", "Adjustment amount when clicking"),
            Map.entry("style", "Display style"),
            Map.entry("target", "Plugin receiving the language selection"),
            Map.entry("type", "Object or parameter type"),
            Map.entry("up", "Direction at the top of the projection"),
            Map.entry("usage", "Command syntax"),
            Map.entry("value", "Current or selected value"),
            Map.entry("variables", "Allowed message placeholders"),
            Map.entry("whitelisted", "Allowed players"),
            Map.entry("world", "World name"),
            Map.entry("x", "X coordinate"),
            Map.entry("y", "Y coordinate"),
            Map.entry("z", "Z coordinate"));

    private WormholesLanguageHeader() {
    }

    static List<String> english() {
        return LanguageFileHeader.render(new LanguageFileHeader.Options(
                "Wormholes", "en_US",
                List.of("Message prefixes are part of their templates. {prefix} is a portal import code prefix."),
                List.of("Colors use &0-&f; formatting uses &k-&r (&l = bold, &r = reset).",
                        "Hex colors support &#RRGGBB, &xRRGGBB, &x&R&R&G&G&B&B and [RRGGBB]."),
                VARIABLES));
    }
}
