modLoader = "javafml"
loaderVersion = "[66,67)"
license = "GPL-3.0"

[[mods]]
modId = "wormholes_clientgametest"
version = "${version}"
displayName = "Wormholes Client GameTest"
description = "Through-portal projection and traversal."
authors = "Volmit Software"

[[dependencies.wormholes_clientgametest]]
modId = "wormholes"
mandatory = true
versionRange = "[${version}]"
ordering = "AFTER"
side = "BOTH"

[[dependencies.wormholes_clientgametest]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion}]"
ordering = "NONE"
side = "BOTH"
