pluginManagement {
    repositories {
        maven { url = uri('https://maven.neoforged.net/releases/') }
        maven { url = uri('https://maven.minecraftforge.net/') }
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id 'org.gradle.toolchains.foojay-resolver-convention' version '1.0.0'
}

rootProject.name = 'wormholes-neoforge'
include(':core')
project(':core').projectDir = file('../../core')
include(':clientTestHost')
project(':clientTestHost').projectDir = file('../forge')

apply from: file('../../gradle/localization-settings.gradle')
