modLoader = "javafml"
loaderVersion = "[66,67)"
license = "GPL-3.0"

[[mods]]
modId = "wormholes"
version = "${version}"
displayName = "Wormholes GameTest"
description = "Through-portal projection and traversal."
authors = "Volmit Software"

[[dependencies.wormholes]]
modId = "forge"
mandatory = true
versionRange = "[66,67)"
ordering = "NONE"
side = "BOTH"

[[dependencies.wormholes]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraftVersion}]"
ordering = "NONE"
side = "BOTH"
